export const PURCHASES_ACTION_TYPES = {
  SET_PURCHASES: 'purchases/SET_PURCHASES',
  SET_NOTIFICATION_PURCHASES: 'purchases/SET_NOTIFICATION_PURCHASES',
  UPDATE_PURCHASES_START: 'purchases/UPDATE_PURCHASES_START',
  UPDATE_PURCHASES_SUCCESS: 'purchases/UPDATE_PURCHASES_SUCCESS',
  UPDATE_PURCHASES_FAILED: 'purchases/UPDATE_PURCHASES_FAILED'
}