export const BASKET_ACTION_TYPES = {
  SET_IS_BASKET_OPEN: 'basket/SET_IS_BASKET_OPEN',
  SET_BASKET: 'basket/SET_BASKET',
  SET_BASKET_TOTAL_START: 'basket/SET_BASKET_TOTAL_START',
  SET_BASKET_TOTAL_SUCCESS: 'basket/SET_BASKET_TOTAL_SUCCESS',
  SET_BASKET_TOTAL_FAILED: 'basket/SET_BASKET_TOTAL_FAILED',
  SET_SEARCH_ITEMS: 'basket/SET_SEARCH_ITEMS',
  UPDATE_SEARCH_ITEMS_AFTER_BASKET_UPDATE_START: 'basket/UPDATE_SEARCH_ITEMS_AFTER_BASKET_UPDATE_START',
  UPDATE_SEARCH_ITEMS_AFTER_BASKET_UPDATE_SUCCESS: 'basket/UPDATE_SEARCH_ITEMS_AFTER_BASKET_UPDATE_SUCCESS',
  UPDATE_SEARCH_ITEMS_AFTER_BASKET_UPDATE_FAILED: 'basket/UPDATE_SEARCH_ITEMS_AFTER_BASKET_UPDATE_FAILED'
}