export const PRODUCTS_ACTION_TYPES = {
  GET_PRODUCTS_START: 'products/GET_PRODUCTS_START',
  GET_PRODUCTS_SUCCESS: 'products/GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILED: 'products/GET_PRODUCTS_FAILED',
  SET_PRODUCT_TARGET_REF: 'products/SET_PRODUCT_TARGET_REF'
}