export const PRODUCTS_ACTION_TYPES = {
  GET_PRODUCTS_START: 'products/GET_PRODUCTS_START',
  GET_PRODUCTS_SUCCESS: 'products/GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILED: 'products/GET_PRODUCTS_FAILED',
  GET_PRODUCT_IMAGES_START: 'products/GET_PRODUCT_IMAGES_START',
  GET_PRODUCT_IMAGES_SUCCESS: 'products/GET_PRODUCT_IMAGES_SUCCESS',
  GET_PRODUCT_IMAGES_FAILED: 'products/GET_PRODUCT_IMAGES_FAILED',
  SET_PRODUCT_TARGET_REF: 'products/SET_PRODUCT_TARGET_REF',
  SET_PRODUCT_IMAGES: 'products/SET_PRODUCT_IMAGES'
}